#### 데이터 설명 : 비행탑승 경험 만족도
#### x_train: https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_train.csv
#### x_test: https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_test.csv
출처 (참고, 데이터 수정)

In [31]:
import pandas as pd
train = pd.read_csv(r'C:\Users\user\OneDrive\문서\카카오톡 받은 파일\train.csv')
test = pd.read_csv(r'C:\Users\user\OneDrive\문서\카카오톡 받은 파일\test.csv')

In [32]:
train.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [33]:
test.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied

## 1. MinMaxScaler

### Question. train 데이터의 Age 컬럼을 MinMax 스케일링하여 얻은 값을 age_mm_scaling 컬럼에 추가한 후, train셋과 같은 기준으로 test 데이터의 Age를 스케일링하고 그 결과를 age_mm_scaling 컬럼에 추가하라.

####step1. 'MinMaxScaler'를 사용하기 위한 라이브러리를 import하기

In [34]:
from sklearn.preprocessing import MinMaxScaler

#### step2. MinMaxScaler 객체 생성

In [35]:
mm_scaler = MinMaxScaler()

#### step3. train 데이터의 Age를 2차원 형태로 변환 후 이를 a1이라는 데이터로 저장

In [36]:
a1 = train[['Age']]

#### step4. MinMaxScaler 객체를 사용하여 데이터를 학습

In [37]:
import sklearn
sklearn.set_config(display='text')

mm_scaler.fit(a1)

MinMaxScaler()

#### step5. 학습된 MinMaxScaler 객체를 사용하여 'Age'열의 데이터를 변환하고, 'age_scaling'컬럼에 추가

In [38]:
train['age_mm_scaling'] = mm_scaler.transform(a1)

#### step6. test 데이터에서도 'Age'컬럼을 추출하여 2차원 배열 형태로 변환하고, 학습된 MinMaxScaler 객체를 사용하여 test 데이터의 'Age'열을 변환 후 이를 'age_mm_scaling'컬럼에 추가

In [39]:
a1_test = test[['Age']]
test['age_mm_scaling'] = mm_scaler.transform(a1_test)

## 2. StandardScaler

### Question. train 데이터의 Age 컬럼을 sklearn 모듈을 활용하여 정규화 스케일링한 결과를 age_s_scaling 컬럼에 추가한 후, train셋과 같은 기준으로 test 데이터의 Age를 스케일링하여 age_s_scaling 컬럼에 추가하라.

#### step1. 'StandScaler'를 사용하기 위한 라이브러리를 import하기

In [42]:
from sklearn.preprocessing import StandardScaler

#### step2. StandardScaler 객체 생성

In [43]:
s_scaler = StandardScaler()

#### step3. train 데이터의 Age를 2차원 형태로 변환 후 이를 a1라는 데이터로 저장

In [44]:
a1 = train[['Age']]

#### step4. StandScaler 객체를 사용하여 데이터를 학습

In [45]:
s_scaler.fit(a1)

StandardScaler()

#### step5. 학습된  StandardScaler 객체를 사용하여 'Age'열의 데이터를 변환하고, 'age_s_scaling'컬럼에 추가

In [46]:
train['age_s_scaling'] = s_scaler.transform(a1)

#### step6. test 데이터에서도 'Age'컬럼을 추출하여 2차원 배열 형태로 변환하고, 학습된 StandardScaler 객체를 사용하여 test데이터의 'Age'열을 변환 후 'age_s_scaling'컬럼에 추가

In [47]:
a1_test = test[['Age']]
test['age_s_scaling'] = s_scaler.transform(a1_test)

#### train 데이터에 추가된 age_mm_scaling 칼럼과 age_s_scaling 칼럼 확인하기

In [48]:
train.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,age_mm_scaling,age_s_scaling
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,3,4,4,5,5,25,18.0,neutral or dissatisfied,0.076923,-1.745279
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,5,3,1,4,1,1,6.0,neutral or dissatisfied,0.230769,-0.951360
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,3,4,4,4,5,0,0.0,satisfied,0.243590,-0.885200
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,5,3,1,4,2,11,9.0,neutral or dissatisfied,0.230769,-0.951360
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,4,4,3,3,3,0,0.0,satisfied,0.692308,1.430397

#### test 데이터에 추가된 age_mm_scaling 칼럼과 age_s_scaling 칼럼 확인하기

In [49]:
test.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,age_mm_scaling,age_s_scaling
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,2,5,5,50,44.0,satisfied,0.576923,0.834958
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,3,4,5,0,0.0,satisfied,0.371795,-0.223601
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,1,3,2,2,2,0,0.0,neutral or dissatisfied,0.166667,-1.282160
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,3,1,4,0,6.0,satisfied,0.474359,0.305678
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,4,2,4,0,20.0,satisfied,0.538462,0.636478